### ISSUE TITLE
In swagger editor, when generated json file, generates several errors; the sample error is:

### ISSUE THREAD

**Issue by harica** [bobby-brennan/fhir-swagger#3]
Hi:
I have just imported the file in your out folder swagger.json file into swagger editor and got several errors. Could you please clarify the error, and a fix, if it is possible. I am new to swagger ....

**Comment by harica** [comment]
✖ Swagger Error
Not a valid schema items definition
Jump to line 120
Details
 Object
✖ Swagger Error
Not a valid schema items definition
Jump to line 106
Details
 Object
✖ Swagger Error
Not a valid schema items definition
Jump to line 92
Details
 Object
✖ Swagger Error
Not a valid schema items definition
Jump to line 82
Details
 Object
✖ Swagger Error
Not a valid schema items definition
Jump to line 46
Details
 Object
✖ Swagger Error
A deterministic version of a JSON Schema object.
Jump to line 3
Details
 Object
code:  "OBJECT_ADDITIONAL_PROPERTIES"
 params: Array [1]
message:  "Additional properties not allowed: $schema"
 path: Array [2]
schemaId:  "http://swagger.io/v2/schema.json#"
description:  "A deterministic version of a JSON Schema object."
level: 900
type:  "Swagger Error"
lineNumber: 3

**Comment by harica** [comment]
The sample of repeated error is as below:
✖ Swagger Error
Not a valid schema items definition
Jump to line 120
Details
 Object
✖ Swagger Error
Not a valid schema items definition
Jump to line 106
Details
 Object
✖ Swagger Error
Not a valid schema items definition
Jump to line 92
Details
 Object
✖ Swagger Error
Not a valid schema items definition
Jump to line 82
Details
 Object
✖ Swagger Error
Not a valid schema items definition
Jump to line 46
Details
 Object
✖ Swagger Error
A deterministic version of a JSON Schema object.
Jump to line 3
Details
 Object
code:  "OBJECT_ADDITIONAL_PROPERTIES"
 params: Array [1]
message:  "Additional properties not allowed: $schema"
 path: Array [2]
schemaId:  "http://swagger.io/v2/schema.json#"
description:  "A deterministic version of a JSON Schema object."
level: 900
type:  "Swagger Error"
lineNumber: 3

**Comment by rbren** [comment]
Validation should pass now in version 2.2.0
